# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8e11f8acf76c3ffc76bfdbe5111dbc0a30175ad28c5d00d8a03411f9697922d627bed0ce6db6b40ab43d01b3f3b46b013ab0715dc01dd6af205f5e1e46b8f9

test:
  secret_key_base: 4f2f5fb0d2d8aac02defbc49df1cd568b544997d5572c5990365a564b6968ab1521d338bac5baec9bad6097f8161914c396d939de3e3f657bbe47265d1f30c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
